# Generated by Django 5.2.15 on 2026-07-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0001_initial_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteComplianceSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='固定编号')),
                ('icp_record_number', models.CharField(blank=True, default='', help_text='请照工信部/备案服务商下发的完整号码填写，例如：闽ICP备XXXXXXXX号。', max_length=80, verbose_name='ICP备案号')),
                ('police_record_number', models.CharField(blank=True, default='', help_text='审核通过后填写完整号码，例如：闽公网安备 XXXXXXXXXXXXXX号；未取得时留空。', max_length=80, verbose_name='公安联网备案号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '网站合规信息',
                'verbose_name_plural': '网站合规信息',
                'db_table': 'site_compliance_settings',
            },
        ),
    ]
