# Generated by Django 5.2.15 on 2026-07-15 03:46

import django.core.validators
import waimai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0002_site_compliance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecompliancesettings',
            name='police_record_icon',
            field=models.ImageField(blank=True, help_text='请上传公安备案审核平台为本网站提供的图标；支持 PNG、JPG、JPEG，最大 1 MB。', upload_to='site_compliance/police/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), waimai.models.validate_compliance_icon_size], verbose_name='公安备案图标'),
        ),
    ]
