# Generated by Django 5.2.15 on 2026-07-16 02:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0003_site_compliance_police_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHomePage',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='固定编号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器主页',
                'verbose_name_plural': '服务器主页',
                'db_table': 'server_home_page',
            },
        ),
        migrations.CreateModel(
            name='ServerSiteSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='固定编号')),
                ('site_name', models.CharField(blank=True, default='野草系统', max_length=80, verbose_name='网站顶部名称')),
                ('brand_image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='标识图片链接（可选）')),
                ('nav_brand_label', models.CharField(blank=True, default='店铺名录', max_length=40, verbose_name='导航「名录」显示名')),
                ('show_powered_by', models.BooleanField(default=True, verbose_name='页脚显示「由野草系统提供支持」')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器站点设置',
                'verbose_name_plural': '服务器站点设置',
                'db_table': 'server_site_settings',
            },
        ),
        migrations.AlterModelOptions(
            name='shophomepage',
            options={'verbose_name': '店铺主页', 'verbose_name_plural': '店铺主页'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_server_owner',
            field=models.BooleanField(db_index=True, default=False, verbose_name='服务器拥有者'),
        ),
        migrations.AlterField(
            model_name='shophomepage',
            name='is_server_entry',
            field=models.BooleanField(db_index=True, default=False, verbose_name='（已弃用）曾作本服务器默认入口'),
        ),
        migrations.CreateModel(
            name='ServerHomeBlock',
            fields=[
                ('block_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='块ID')),
                ('block_type', models.CharField(db_index=True, max_length=32, verbose_name='块类型')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='正文')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='图片链接')),
                ('link_url', models.CharField(blank=True, default='', max_length=500, verbose_name='附加链接')),
                ('nav_label', models.CharField(blank=True, default='', max_length=32, verbose_name='导航短名')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='是否启用')),
                ('show_in_nav', models.BooleanField(default=True, verbose_name='是否出现在吸顶导航')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='waimai.serverhomepage', verbose_name='所属服务器主页')),
            ],
            options={
                'verbose_name': '服务器主页积木块',
                'verbose_name_plural': '服务器主页积木块',
                'db_table': 'server_home_block',
                'ordering': ['sort_order', 'block_type'],
                'constraints': [models.UniqueConstraint(fields=('home_page', 'block_type'), name='uniq_server_home_block_type')],
            },
        ),
    ]
