# Generated by Django 5.2.15 on 2026-07-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0004_server_shop_home_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_server_owner',
            field=models.BooleanField(db_index=True, default=False, verbose_name='服务器管理者'),
        ),
    ]
