# Generated by Django 5.2.15 on 2026-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0005_server_manager_verbose'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serverhomeblock',
            name='uniq_server_home_block_type',
        ),
        migrations.RemoveConstraint(
            model_name='shophomeblock',
            name='uniq_home_block_type',
        ),
        migrations.AddConstraint(
            model_name='serverhomeblock',
            constraint=models.UniqueConstraint(condition=models.Q(('block_type', 'custom'), _negated=True), fields=('home_page', 'block_type'), name='uniq_server_home_block_type_non_custom'),
        ),
        migrations.AddConstraint(
            model_name='shophomeblock',
            constraint=models.UniqueConstraint(condition=models.Q(('block_type', 'custom'), _negated=True), fields=('home_page', 'block_type'), name='uniq_shop_home_block_type_non_custom'),
        ),
    ]
