# Generated by Django 5.2.15 on 2026-07-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0006_home_custom_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophomepage',
            name='order_nav_mode',
            field=models.CharField(choices=[('to_shop', '导航「下单」直接进下单页'), ('to_cta_block', '导航「下单」滚到页内「进入店铺」块')], default='to_shop', max_length=16, verbose_name='顶栏下单行为'),
        ),
    ]
