# Generated by Django 5.2.15 on 2026-07-16 04:24

import django.core.validators
import django.db.models.deletion
import uuid
import waimai.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0007_order_nav_label_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhomeblock',
            name='image',
            field=models.ImageField(blank=True, upload_to=waimai.models.home_block_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif']), waimai.models.validate_home_block_image_size], verbose_name='上传配图'),
        ),
        migrations.AddField(
            model_name='shophomeblock',
            name='image',
            field=models.ImageField(blank=True, upload_to=waimai.models.home_block_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif']), waimai.models.validate_home_block_image_size], verbose_name='上传配图'),
        ),
        migrations.AlterField(
            model_name='serverhomeblock',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='图片公开链接'),
        ),
        migrations.AlterField(
            model_name='shophomeblock',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='图片公开链接'),
        ),
        migrations.CreateModel(
            name='UserUploadedPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('scope', models.CharField(choices=[('shop_home_block', '店铺主页积木'), ('server_home_block', '服务器主页积木')], db_index=True, max_length=32, verbose_name='用途')),
                ('block_id', models.UUIDField(db_index=True, verbose_name='积木块ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '用户上传配图',
                'verbose_name_plural': '用户上传配图',
                'db_table': 'user_uploaded_photo',
                'constraints': [models.UniqueConstraint(fields=('owner', 'scope', 'block_id'), name='uniq_owner_block_photo')],
            },
        ),
    ]
