# Generated by Django 5.2.15 on 2026-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0008_home_block_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='takeaway_channel_enabled',
            field=models.BooleanField(default=True, verbose_name='当前打包接单开'),
        ),
    ]
