# Generated by Django 5.2.15 on 2026-07-16 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0009_takeaway_channel_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='buyer_msg_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='买家已读沟通时间'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='seller_msg_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='店家已读沟通时间'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='order_status',
            field=models.CharField(choices=[('awaiting_payment', '待支付'), ('awaiting_shop_confirm', '待店家备货'), ('awaiting_prep', '待备货'), ('preparing', '商家备货中'), ('ready_pickup', '待取货'), ('delivering', '配送中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='awaiting_payment', max_length=24, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='留言ID')),
                ('author_side', models.CharField(choices=[('buyer', '买家'), ('shop', '店家')], db_index=True, max_length=8, verbose_name='发言方')),
                ('author_username', models.CharField(max_length=128, verbose_name='发言账号')),
                ('body', models.CharField(max_length=300, verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='waimai.buyorder', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单沟通留言',
                'verbose_name_plural': '订单沟通留言',
                'db_table': 'order_message',
                'ordering': ['created_at'],
            },
        ),
    ]
