# Generated by Django 5.2.15 on 2026-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0010_order_message_and_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='cancel_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='取消说明'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cancel_side',
            field=models.CharField(blank=True, choices=[('buyer', '买家'), ('shop', '店家')], default='', max_length=8, verbose_name='取消方'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='perm_cancel_order',
            field=models.BooleanField(default=False, help_text='店主授权后，该员工可在满足沟通门槛时取消订单', verbose_name='允许取消订单'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', '买家'), ('seller', '卖家'), ('rider', '骑手'), ('waiter', '服务员'), ('kitchen', '后厨'), ('manager', '店长')], default='buyer', max_length=10, verbose_name='用户身份'),
        ),
    ]
