# Generated by Django 5.2.15 on 2026-07-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0011_manager_role_and_order_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppaymentsettings',
            name='is_showcase_shop',
        ),
    ]
