# Generated by Django 5.2.15 on 2026-07-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0012_remove_shoppaymentsettings_is_showcase_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='alert_interval_sec',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='提醒重复间隔（秒）'),
        ),
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='alert_sound',
            field=models.FileField(blank=True, null=True, upload_to='alert_sounds/', verbose_name='自定义提醒音频（留空用系统默认提示音）'),
        ),
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='alert_volume',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='提醒音量（0～100）'),
        ),
    ]
