# Generated by Django 5.2.15 on 2026-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0013_shopoperatingsettings_alert_interval_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='order_notify_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='新订单通知收件邮箱（多个用逗号分隔）'),
        ),
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='order_notify_enabled',
            field=models.BooleanField(default=False, verbose_name='开启新订单邮件通知'),
        ),
    ]
