# Generated by Django 5.2.15 on 2026-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0014_shopoperatingsettings_order_notify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='guest_nickname',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='称呼（可选）'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='buyer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='买家ID'),
        ),
    ]
