# Generated by Django 5.2.15 on 2026-07-18 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0015_buyorder_guest_nickname_and_blank_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='delivery_default_wait_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='外卖默认等待时间（分钟）'),
        ),
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='dine_default_wait_minutes',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='堂食默认等待时间（分钟）'),
        ),
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='takeaway_default_wait_minutes',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='打包默认等待时间（分钟）'),
        ),
        migrations.CreateModel(
            name='ShopWaitTimeRule',
            fields=[
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('dine_in', '堂食'), ('takeaway', '打包'), ('delivery', '外卖')], max_length=16, verbose_name='订单类型')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('wait_minutes', models.PositiveSmallIntegerField(verbose_name='等待时间（分钟）')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_time_rules', to='waimai.shopoperatingsettings', verbose_name='所属店铺营业设置')),
            ],
            options={
                'verbose_name': '分时段等待时间',
                'verbose_name_plural': '分时段等待时间',
                'db_table': 'shop_wait_time_rule',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
    ]
