# Generated by Django 5.2.15 on 2026-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0016_shopoperatingsettings_delivery_default_wait_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='cash_collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='骑手实收现金（元）'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='骑手收款时间'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_collected_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='收款骑手'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_remitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入金确认时间'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_remitted_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='入金确认人'),
        ),
        migrations.AddField(
            model_name='shoppaymentsettings',
            name='enable_cod',
            field=models.BooleanField(default=True, verbose_name='允许外卖现金货到付款'),
        ),
    ]
