# Generated by Django 5.2.15 on 2026-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0017_buyorder_cash_collected_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='table_lan_base_url',
            field=models.CharField(blank=True, default='', help_text='如 http://192.168.1.10:8000 ；仅店内访客 WiFi 可访问。勿填宽带公网 IP。', max_length=255, verbose_name='桌码局域网固定地址'),
        ),
    ]
