# Generated by Django 5.2.15 on 2026-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0018_table_lan_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='plugin_dining_enabled',
            field=models.BooleanField(default=True, help_text='关闭后卖家后台隐藏「堂食营业」入口；业务数据不删，只是先像插件一样可停用。', verbose_name='启用饮食插件（试验）'),
        ),
    ]
