# Generated by Django 5.x for fulfillment plugin switch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0022_rename_delivery_staff_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopoperatingsettings',
            name='plugin_fulfillment_enabled',
            field=models.BooleanField(
                default=True,
                help_text='关闭后隐藏「配送费规则」与工作台配送页签；已有配送单与权限保留。',
                verbose_name='启用履约配送插件（试验）',
            ),
        ),
    ]
