# Generated by Django 5.2.15 on 2026-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0023_plugin_fulfillment_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopoperatingsettings',
            name='plugin_fulfillment_enabled',
            field=models.BooleanField(default=True, help_text='关闭后：不接新外卖单；隐藏配送费规则、工作台配送页签、货到付款入金；已有配送单与权限保留。', verbose_name='启用履约配送插件（试验）'),
        ),
    ]
