# Generated by Django 5.2.15 on 2026-07-19 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0025_user_active_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRemittanceRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='交款申请ID')),
                ('seller_id', models.CharField(db_index=True, max_length=64, verbose_name='店铺ID')),
                ('rider_id', models.CharField(db_index=True, max_length=64, verbose_name='配送员ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='申请交款金额（元）')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='包含订单数')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='配送员交款备注')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已退回')], db_index=True, default='pending', max_length=16, verbose_name='交款申请状态')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='确认/退回人')),
                ('review_note', models.CharField(blank=True, default='', max_length=500, verbose_name='确认/退回说明')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配送员现金交款申请',
                'verbose_name_plural': '配送员现金交款申请',
                'db_table': 'cash_remittance_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_exception_marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='现金异常标记时间'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_exception_marked_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='现金异常标记人'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_exception_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='现金异常电话沟通备注'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_exception_resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='现金异常处理时间'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_exception_resolved_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='现金异常处理人'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_shortfall_buyer_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='买家确认少收时间'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_shortfall_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='货到付款少收原因'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='cash_shortfall_status',
            field=models.CharField(blank=True, choices=[('', '无异常'), ('buyer_pending', '待买家确认少付'), ('buyer_confirmed', '买家已确认少付'), ('buyer_rejected', '买家拒绝确认'), ('exception', '已电话上报异常'), ('manager_approved', '管理人员已兜底结单')], db_index=True, default='', max_length=24, verbose_name='货到付款少收状态'),
        ),
        migrations.CreateModel(
            name='CashRemittanceItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='交款明细ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='本单实收（元）')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_remittance_items', to='waimai.buyorder', verbose_name='现金订单')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waimai.cashremittancerequest', verbose_name='交款申请')),
            ],
            options={
                'verbose_name': '配送员现金交款明细',
                'verbose_name_plural': '配送员现金交款明细',
                'db_table': 'cash_remittance_item',
                'constraints': [models.UniqueConstraint(fields=('request', 'order'), name='uniq_cash_remittance_request_order')],
            },
        ),
    ]
