# Generated by Django 5.2.15 on 2026-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0026_cashremittancerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='cash_shortfall_status',
            field=models.CharField(blank=True, choices=[('', '无异常'), ('buyer_pending', '待买家确认少付'), ('buyer_confirmed', '买家已确认少付'), ('buyer_rejected', '买家拒绝确认'), ('exception', '已电话上报异常'), ('resolved_full', '已补足现金'), ('manager_approved', '管理人员已兜底结单')], db_index=True, default='', max_length=24, verbose_name='货到付款少收状态'),
        ),
    ]
