# Generated by Django 5.2.15 on 2026-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0036_shop_cashier_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wechat_simulate', '微信扫码支付（模拟）'), ('wechat', '微信支付'), ('cash', '现金'), ('external', '外部门店收款'), ('card', '信用卡/借记卡')], max_length=20, null=True, verbose_name='支付渠道'),
        ),
    ]
