# Generated by Django 5.2.15 on 2026-07-29 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0037_alter_buyorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendancelog',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间'),
        ),
    ]
