# Generated by Django 5.2.15 on 2026-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0038_staff_attendance_changed_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhomeblock',
            name='link_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='附加链接显示文字'),
        ),
        migrations.AddField(
            model_name='shophomeblock',
            name='link_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='附加链接显示文字'),
        ),
    ]
