# Generated by Django 5.x · 84a 资金总流水

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waimai', '0048_remove_dish_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundLedgerEntry',
            fields=[
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='流水ID')),
                ('display_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='流水号')),
                ('seller_id', models.CharField(db_index=True, max_length=64, verbose_name='店铺')),
                ('direction', models.CharField(choices=[('income', '收入'), ('expense', '支出')], db_index=True, max_length=8, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='金额')),
                ('payment_method', models.CharField(db_index=True, max_length=32, verbose_name='支付方式')),
                ('fund_status', models.CharField(blank=True, choices=[('not_applicable', '不涉及真钱'), ('customer_paid', '客人侧已付'), ('in_transit', '在途'), ('at_shop', '已到店铺'), ('written_off', '未收款结案')], default='', max_length=32, verbose_name='资金状态')),
                ('refund_status', models.CharField(blank=True, choices=[('refund_pending', '待处理'), ('refund_processing', '处理中'), ('refund_completed', '退款已完成'), ('refund_rejected', '已驳回')], default='', max_length=32, verbose_name='退款状态')),
                ('business_type', models.CharField(db_index=True, max_length=48, verbose_name='业务类型')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='来源入口')),
                ('entry_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已撤销')], db_index=True, default='success', max_length=16, verbose_name='流水状态')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(blank=True, default='', max_length=128, verbose_name='操作人')),
                ('reference_key', models.CharField(blank=True, default='', max_length=128, verbose_name='依据编号')),
                ('schema_version', models.CharField(default='1', max_length=16, verbose_name='规则版本')),
                ('app_build', models.CharField(blank=True, default='', max_length=32, verbose_name='应用版本')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_ledger_entries', to='waimai.buyorder', verbose_name='关联订单')),
                ('related_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_entries', to='waimai.fundledgerentry', verbose_name='关联流水')),
            ],
            options={
                'verbose_name': '资金总流水',
                'verbose_name_plural': '资金总流水',
                'db_table': 'fund_ledger_entry',
                'ordering': ['-occurred_at', '-ledger_id'],
            },
        ),
        migrations.CreateModel(
            name='FundLedgerStatusTrack',
            fields=[
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='追踪ID')),
                ('changed_field', models.CharField(max_length=32, verbose_name='变更字段')),
                ('value_before', models.CharField(blank=True, default='', max_length=64, verbose_name='变更前')),
                ('value_after', models.CharField(blank=True, default='', max_length=64, verbose_name='变更后')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='变更时间')),
                ('operator', models.CharField(blank=True, default='', max_length=128, verbose_name='操作人')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='来源')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tracks', to='waimai.fundledgerentry', verbose_name='关联流水')),
            ],
            options={
                'verbose_name': '资金流水状态追踪',
                'verbose_name_plural': '资金流水状态追踪',
                'db_table': 'fund_ledger_status_track',
                'ordering': ['changed_at', 'track_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fundledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_key__gt', '')), fields=('seller_id', 'reference_key'), name='uniq_fund_ledger_seller_reference'),
        ),
    ]
