"""
Django settings for wuwei_system project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv_if_present(path: Path) -> None:
    """若存在 .env 则载入（不覆盖已有环境变量；.env 不进 Git）"""
    if not path.is_file():
        return
    try:
        text = path.read_text(encoding='utf-8')
    except OSError:
        return
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, val = line.partition('=')
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = val


_load_dotenv_if_present(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 是否调试：本机默认开；云上正式运行须设 YECAO_DEBUG=0
DEBUG = os.environ.get('YECAO_DEBUG', '1') == '1'

# 网站签名钥匙：优先读环境变量，切勿把真钥匙写进代码再推公开仓
# 云上必设：DJANGO_SECRET_KEY 或 YECAO_SECRET_KEY（用全新一串，不要用本机占位）
SECRET_KEY = (
    os.environ.get('DJANGO_SECRET_KEY')
    or os.environ.get('YECAO_SECRET_KEY')
    or ''
).strip()
if not SECRET_KEY:
    if DEBUG:
        # 仅本机开发占位，公网部署不可用
        SECRET_KEY = 'django-insecure-local-dev-only-not-for-production'
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            '生产环境必须设置环境变量 DJANGO_SECRET_KEY（或 YECAO_SECRET_KEY）'
        )

def _get_lan_ip_for_dev():
    """开发阶段：自动识别本机局域网 IP，方便手机连同一 WiFi 测试"""
    import socket
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.connect(('8.8.8.8', 80))
        ip = sock.getsockname()[0]
        sock.close()
        return ip
    except OSError:
        return None


# 本机访问 + 开发时允许局域网 IP（手机用 http://电脑IP:8000 访问）
# 云上可再设 YECAO_ALLOWED_HOSTS=域名,公网IP（逗号分隔）
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
_extra_hosts = os.environ.get('YECAO_ALLOWED_HOSTS', '').strip()
if _extra_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in _extra_hosts.split(',') if h.strip()])
if DEBUG:
    _lan = _get_lan_ip_for_dev()
    if _lan:
        ALLOWED_HOSTS.append(_lan)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'waimai.apps.WaimaiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'waimai.middleware.ShopWorkAuthMiddleware',
    'waimai.middleware.ExperienceOnlineMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wuwei_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'waimai.context_processors.nav_shop_work',
                'waimai.context_processors.experience_site',
                'waimai.context_processors.site_compliance',
                'waimai.context_processors.site_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'wuwei_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'  # 全站展示统一为北京时间（UTC+8）

USE_I18N = True

USE_TZ = True  # 库内用 UTC 存，页面展示经 localtime / |beijing 转北京时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# 生产收集静态文件的目录（collectstatic）；本地可不跑该命令。目录已在 .gitignore
STATIC_ROOT = BASE_DIR / 'staticfiles'
# 服务器拥有者上传的备案图标等文件；目录不进 Git，生产环境由 Nginx 提供访问。
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# 主页积木配图单张上限 5MB，请求体略放大以免被默认 2.5MB 拦住
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'waimai.User'
# 登出后跳转到登录页面
LOGOUT_REDIRECT_URL = '/accounts/login/'

# 关闭浏览器后登录状态失效，下次必须重新验证（公共电脑安全）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# 会话寿命与「约 5 分钟无报平安」对齐：页面会定时心跳刷新；关页后约 5 分钟失效
SESSION_COOKIE_AGE = 5 * 60
SESSION_SAVE_EVERY_REQUEST = False

# ---------- 体验机模式（默认关闭；云上公网体验机设 YECAO_EXPERIENCE_SITE=1）----------
YECAO_EXPERIENCE_SITE = os.environ.get('YECAO_EXPERIENCE_SITE', '0') == '1'
YECAO_EXPERIENCE_DAILY_SHOPS = int(os.environ.get('YECAO_EXPERIENCE_DAILY_SHOPS', '15'))
YECAO_EXPERIENCE_DAILY_ACCOUNTS = int(os.environ.get('YECAO_EXPERIENCE_DAILY_ACCOUNTS', '30'))
YECAO_EXPERIENCE_CONCURRENT = int(os.environ.get('YECAO_EXPERIENCE_CONCURRENT', '10'))
YECAO_EXPERIENCE_NOTIFY_EMAIL = os.environ.get('YECAO_EXPERIENCE_NOTIFY_EMAIL', '').strip()

# ---------- 邮件发送（新订单通知等）----------
# 未在 .env 填写发信邮箱时不会发邮件，也不会报错（YECAO_EMAIL_READY 为 False）。
EMAIL_HOST = os.environ.get('YECAO_EMAIL_HOST', '').strip()
EMAIL_PORT = int(os.environ.get('YECAO_EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.environ.get('YECAO_EMAIL_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('YECAO_EMAIL_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('YECAO_EMAIL_TLS', '0') == '1'
# 465 端口用 SSL；587 端口用 TLS。两者不能同时开。
EMAIL_USE_SSL = (os.environ.get('YECAO_EMAIL_SSL', '1') == '1') and not EMAIL_USE_TLS
DEFAULT_FROM_EMAIL = os.environ.get('YECAO_EMAIL_FROM', '').strip() or EMAIL_HOST_USER
EMAIL_TIMEOUT = 10
# 三项齐全才认为发信邮箱可用；否则通知逻辑直接跳过，避免卡顿或报错。
YECAO_EMAIL_READY = bool(EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)

# ---------- A.12 技术运行日志（文件不进 Git；普通约 30 天、错误/支付约 90 天）----------
YECAO_LOG_DIR = BASE_DIR / 'logs'
YECAO_LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'runtime_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(YECAO_LOG_DIR / 'runtime.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'standard',
        },
        'error_payment_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(YECAO_LOG_DIR / 'error_payment.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 90,
            'encoding': 'utf-8',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'waimai': {
            'handlers': ['runtime_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'waimai.payment': {
            'handlers': ['error_payment_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_payment_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}